name: sip + elfak

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sip.py
        run:
          python sip.py

      - name: Get current hour
        id: time
        run: |
          CURRENT_HOUR=$(date +'%H')
          echo "Current hour: $CURRENT_HOUR"
          echo "current_hour=$CURRENT_HOUR" >> $GITHUB_OUTPUT

      - name: Run cs_elfak.py (morning 6–8 or night 20–1)
        if: ${{ (steps.time.outputs.current_hour >= 6 && steps.time.outputs.current_hour < 8) || (steps.time.outputs.current_hour >= 20 || steps.time.outputs.current_hour < 1) }}
        env:
          SAJT: ${{ secrets.SAJT }}
          MAIL: ${{ secrets.MAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python cs_elfak.py

      - name: Check for real changes
        id: changes
        run: |
          git add *.md
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.changed == 'true'
        uses: lazarevicOgnjen/git-auto-commit-action@v6
        with:
          commit_message: Update markdown
          file_pattern: "*.md"

      - name: Detect per-file changes
        id: detect
        if: steps.changes.outputs.changed == 'true'
        run: |
          for f in bp.md sp.md pj.md oopj.md lp.md oop.md aor1.md dmat.md sip.md aip.md uur.md; do
            if git diff --name-only HEAD~1 HEAD | grep -q $f; then
              echo "${f%.md}_changed=true" >> $GITHUB_OUTPUT
            else
              echo "${f%.md}_changed=false" >> $GITHUB_OUTPUT
            fi
          done

     
        
      - name: SIP notification
        if: steps.detect.outputs.sip_changed == 'true'
        env:
          BOT_MAIL: ${{ secrets.BOT_MAIL }}
          BOT_PASS: ${{ secrets.BOT_PASS }}
        run: python sip_send.py

      - name: UUR notification
        if: steps.detect.outputs.uur_changed == 'true'
        env:
          BOT_MAIL: ${{ secrets.BOT_MAIL }}
          BOT_PASS: ${{ secrets.BOT_PASS }}
        run: python uur_send.py
